name: test
on: [push, pull_request]
jobs:
  build-test-nix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stuff:
          - flake: IA-32
            step_config: make alldefconfig MAKE_ARCH=x86 && make tests MAKE_ARCH=x86
            step_build: make MAKE_ARCH=x86 CROSS_COMPILE=i686-elf-
            step_bootimg: make bootimg-x86-32 MAKE_ARCH=x86
            nm: i686-elf-nm
            runcmd: qemu-system-x86_64 -cdrom vix.iso -nographic
            ignore_test_failure: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v28
      - name: Build development environment
        shell: echo $(env) {0}
        run: echo a
      - name: Build development environment
        run: echo yeah ${{ matrix.stuff.flake }}
      - name: run kconfig
        shell: nix develop .#IA-32 --command bash -e {0}
        run: |
          echo qwhar?? ${{ matrix.stuff.flake }}
          ${{ matrix.stuff.step_config }}
      #- name: Compile
      #  shell: nix develop .#${{ matrix.stuff.flake }} --command bash -e {0}
      #  run: |
      #    ${{ matrix.stuff.step_build }}
