name: Build
on: [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install nasm gcc-multilib g++-multilib xorriso grub-common mtools qemu-system-x86 llvm-dev libclang-dev clang python3 pkg-config flex bison

      - name: compile
        run: cd $GITHUB_WORKSPACE && make alldefconfig tests all MAKE_ARCH=x86

      - name: run
        run: |
          cd $GITHUB_WORKSPACE
          timeout 30 qemu-system-x86_64 -cdrom shitOS.iso -nographic > log.txt || true
          cat log.txt

      - name: upload image
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: ${{runner.workspace}}/shitOS/shitOS.iso

      - name: count LOC
        run: |
          cd $GITHUB_WORKSPACE 
          python3 tools/locchart.py >> $GITHUB_STEP_SUMMARY

      - name: check tests
        run: |
          cd $GITHUB_WORKSPACE 
          python3 tools/testparser.py log.txt >> $GITHUB_STEP_SUMMARY
          python3 tools/testparser.py log.txt -f

  formatting_and_spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y codespell python3

      - name: codespell
        run: cd $GITHUB_WORKSPACE && codespell -q 3 --builtin clear -S ./.git,./kernel/scripts -L useable || true

      - name: clang-format
        run: cd $GITHUB_WORKSPACE && python3 tools/clang_format_check.py
