name: Build
on: [push, pull_request]
jobs:
  build-x86_32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install nasm gcc-multilib g++-multilib xorriso grub-common mtools qemu-system-x86 llvm-dev libclang-dev clang python3 pkg-config flex bison

      - name: compile
        run: cd $GITHUB_WORKSPACE && make alldefconfig tests all MAKE_ARCH=x86

      - name: run
        run: |
          cd $GITHUB_WORKSPACE
          timeout 30 qemu-system-x86_64 -cdrom shitOS.iso -nographic > log.txt || true
          cat log.txt

      - name: upload image
        uses: actions/upload-artifact@v3
        with:
          name: image-x86_32
          path: ${{runner.workspace}}/shitOS/shitOS.iso

      - name: check tests
        run: |
          cd $GITHUB_WORKSPACE
          python3 tools/testparser.py log.txt >> $GITHUB_STEP_SUMMARY
          python3 tools/testparser.py log.txt -f
  
  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install qemu-system-arm qemu-efi-aarch64 llvm-dev libclang-dev clang python3 pkg-config flex bison gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu git nasm gzip gawk

      - name: build limine
        run: |
          cd $GITHUB_WORKSPACE/../
          git clone https://github.com/limine-bootloader/limine.git
          cd limine
          git checkout v4.20230114.0
          ./bootstrap
          CROSS_TOOLCHAIN=aarch64-linux-gnu ./configure --enable-uefi-aarch64
          make -j $(nproc)

      - name: compile
        run: |
          cd $GITHUB_WORKSPACE
          make alldefconfig tests all MAKE_ARCH=aarch64 CROSS_COMPILE=aarch64-linux-gnu-

      - name: run
        run: |
          cd $GITHUB_WORKSPACE
          timeout 30 qemu-system-aarch64 -m 1024m -bios /usr/share/qemu-efi-aarch64/QEMU_EFI.fd -cpu cortex-a53 -smp 4 -machine virt -device ramfb -device qemu-xhci -device usb-kbd -nographic -serial mon:stdio -hda shitOS_uefi.img > log.txt || true
          cat log.txt

      - name: upload image
        uses: actions/upload-artifact@v3
        with:
          name: image-aarch64
          path: ${{runner.workspace}}/shitOS/shitOS_uefi.img

      - name: check tests
        run: |
          cd $GITHUB_WORKSPACE
          python3 tools/testparser.py log.txt >> $GITHUB_STEP_SUMMARY
          python3 tools/testparser.py log.txt -f

  formatting_and_spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y codespell python3

      - name: count LOC
        run: |
          cd $GITHUB_WORKSPACE 
          python3 tools/locchart.py >> $GITHUB_STEP_SUMMARY

      - name: codespell
        run: cd $GITHUB_WORKSPACE && codespell -q 3 --builtin clear -S ./.git,./kernel/scripts -L useable || true

      - name: clang-format
        run: cd $GITHUB_WORKSPACE && python3 tools/clang_check.py
